export default {
  STUDENT_LIST: 'STUDENT_LIST',
  SET_SHOW: 'SET_SHOW',
  SET_STATUS: 'SET_STATUS',
  SET_TYPE: 'SET_TYPE',
  GET_SUBMIT: 'GET_SUBMIT',
  GET_NO_SUBMIT: 'GET_NO_SUBMIT',
  GET_OPERATION: 'GET_OPERATION',
  SET_UDP_LIST: 'SET_UDP_LIST',
  GET_UDP_LIST: 'GET_UDP_LIST'
}
